using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CCS7Manager
{
    class Countries
    {
        public Dictionary<string, List<string>> CountryList;
        public Countries ()
        {
            CountryList.Add("Afghanistan", new List<string>() { "Afghanistan" });
            CountryList.Add("Albania", new List<string>() { "Albania" });
            CountryList.Add("Algeria", new List<string>() { "Algeria" });
            CountryList.Add("American Samoa", new List<string>() { "American Samoa" });
            CountryList.Add("Andorra", new List<string>() { "Andorra" });
            CountryList.Add("Angola", new List<string>() { "Angola" });
            CountryList.Add("Anguilla", new List<string>() { "Anguilla" });
            CountryList.Add("Antigua and Barbuda", new List<string>()  {"Antigua and Barbuda" });
            CountryList.Add("Argentina Republic", new List<string>() { "Argentina Republic" });
            CountryList.Add("Armenia", new List<string>() { "Armenia" });
            CountryList.Add("Aruba", new List<string>() { "Aruba" });
            CountryList.Add("Australia", new List<string>() { "Australia" });
            CountryList.Add("Austria", new List<string>() { "Austria" });
            CountryList.Add("Azerbaijan", new List<string>() { "Azerbaijan" });
            CountryList.Add("Bahamas", new List<string>() { "Bahamas" });
            CountryList.Add("Bahrain", new List<string>() { "Bahrain" });
            CountryList.Add("Bangladesh", new List<string>() { "Bangladesh" });
            CountryList.Add("Barbados", new List<string>() { "Barbados" });
            CountryList.Add("Belarus", new List<string>() { "Belarus" });
            CountryList.Add("Belgium", new List<string>() { "Belgium" });
            CountryList.Add("Belize", new List<string>() { "Belize" });
            CountryList.Add("Benin", new List<string>() { "Benin" });
            CountryList.Add("Bermuda", new List<string>() { "Bermuda" });
            CountryList.Add("Bhutan", new List<string>() { "Bhutan" });
            CountryList.Add("Bolivia", new List<string>() { "Bolivia" });
            CountryList.Add("Bosnia And Herzegovin", new List<string>() { "Bosnia And Herzegovin" });
            CountryList.Add("Botswana", new List<string>() { "Botswana" });
            CountryList.Add("Brazil", new List<string>() { "Brazil" });
            CountryList.Add("British Virgin Islands", new List<string>() { "British Virgin Islands" });
            CountryList.Add("Brunei Darussalam", new List<string>() { "Brunei Darussalam" });
            CountryList.Add("Bulgaria", new List<string>() { "Bulgaria" });
            CountryList.Add("Burkina Faso", new List<string>() { "Burkina Faso" });
            CountryList.Add("Burma", new List<string>() { "Burma" });
            CountryList.Add("Burundi", new List<string>() { "Burundi" });
            this.chkBoxCountries.Items.Add((object)"Cambodia");
            this.chkBoxCountries.Items.Add((object)"Canada");
            this.chkBoxCountries.Items.Add((object)"Cayman Islands");
            this.chkBoxCountries.Items.Add((object)"Chile");
            this.chkBoxCountries.Items.Add((object)"China");
            this.chkBoxCountries.Items.Add((object)"Colombia");
            this.chkBoxCountries.Items.Add((object)"Comoros");
            this.chkBoxCountries.Items.Add((object)"Congo, Dem. Rep.");
            this.chkBoxCountries.Items.Add((object)"Cook Islands");
            this.chkBoxCountries.Items.Add((object)"Corse");
            this.chkBoxCountries.Items.Add((object)"Costa Rica");
            this.chkBoxCountries.Items.Add((object)"Croatia");
            this.chkBoxCountries.Items.Add((object)"Cuba");
            this.chkBoxCountries.Items.Add((object)"Cyprus");
            this.chkBoxCountries.Items.Add((object)"Czech Republic");
            this.chkBoxCountries.Items.Add((object)"Denmark");
            this.chkBoxCountries.Items.Add((object)"Djibouti");
            this.chkBoxCountries.Items.Add((object)"Dominica");
            this.chkBoxCountries.Items.Add((object)"Dominican Republic");
            this.chkBoxCountries.Items.Add((object)"Ecuador");
            this.chkBoxCountries.Items.Add((object)"Egypt");
            this.chkBoxCountries.Items.Add((object)"El Salvador");
            this.chkBoxCountries.Items.Add((object)"Eritrea");
            this.chkBoxCountries.Items.Add((object)"Estonia");
            this.chkBoxCountries.Items.Add((object)"Ethiopia");
            this.chkBoxCountries.Items.Add((object)"Faroe Islands");
            this.chkBoxCountries.Items.Add((object)"Fiji");
            this.chkBoxCountries.Items.Add((object)"Finland");
            this.chkBoxCountries.Items.Add((object)"France");
            this.chkBoxCountries.Items.Add((object)"French Guiana");
            this.chkBoxCountries.Items.Add((object)"French Polynesia");
            this.chkBoxCountries.Items.Add((object)"Gambia");
            this.chkBoxCountries.Items.Add((object)"Georgia");
            this.chkBoxCountries.Items.Add((object)"Germany");
            this.chkBoxCountries.Items.Add((object)"Gibraltar");
            this.chkBoxCountries.Items.Add((object)"Greece");
            this.chkBoxCountries.Items.Add((object)"Greenland");
            this.chkBoxCountries.Items.Add((object)"Grenada");
            this.chkBoxCountries.Items.Add((object)"Guam");
            this.chkBoxCountries.Items.Add((object)"Guatemala");
            this.chkBoxCountries.Items.Add((object)"Guinea");
            this.chkBoxCountries.Items.Add((object)"Guinea-Bissau");
            this.chkBoxCountries.Items.Add((object)"Guyana");
            this.chkBoxCountries.Items.Add((object)"Haiti");
            this.chkBoxCountries.Items.Add((object)"Honduras");
            this.chkBoxCountries.Items.Add((object)"Hong Kong");
            this.chkBoxCountries.Items.Add((object)"Hungary");
            this.chkBoxCountries.Items.Add((object)"Iceland");
            this.chkBoxCountries.Items.Add((object)"India");
            this.chkBoxCountries.Items.Add((object)"Indonesia");
            this.chkBoxCountries.Items.Add((object)"Iran");
            this.chkBoxCountries.Items.Add((object)"Iraq");
            this.chkBoxCountries.Items.Add((object)"Ireland");
            this.chkBoxCountries.Items.Add((object)"Israel");
            this.chkBoxCountries.Items.Add((object)"Italy");
            this.chkBoxCountries.Items.Add((object)"Ivory Coast");
            this.chkBoxCountries.Items.Add((object)"Jamaica");
            this.chkBoxCountries.Items.Add((object)"Japan");
            this.chkBoxCountries.Items.Add((object)"Jordan");
            this.chkBoxCountries.Items.Add((object)"Kazakhstan");
            this.chkBoxCountries.Items.Add((object)"Kenya");
            this.chkBoxCountries.Items.Add((object)"Kiribati");
            this.chkBoxCountries.Items.Add((object)"Korea S, Republic of");
            this.chkBoxCountries.Items.Add((object)"Kuwait");
            this.chkBoxCountries.Items.Add((object)"Kyrgyzstan");
            this.chkBoxCountries.Items.Add((object)"Laos P.D.R.");
            this.chkBoxCountries.Items.Add((object)"Latvia");
            this.chkBoxCountries.Items.Add((object)"Lebanon");
            this.chkBoxCountries.Items.Add((object)"Lesotho");
            this.chkBoxCountries.Items.Add((object)"Liberia");
            this.chkBoxCountries.Items.Add((object)"Libya");
            this.chkBoxCountries.Items.Add((object)"Liechtenstein");
            this.chkBoxCountries.Items.Add((object)"Lithuania");
            this.chkBoxCountries.Items.Add((object)"Luxembourg");
            this.chkBoxCountries.Items.Add((object)"Macao, China");
            this.chkBoxCountries.Items.Add((object)"Macedonia");
            this.chkBoxCountries.Items.Add((object)"Madagascar");
            this.chkBoxCountries.Items.Add((object)"Malawi");
            this.chkBoxCountries.Items.Add((object)"Malaysia");
            this.chkBoxCountries.Items.Add((object)"Maldives");
            this.chkBoxCountries.Items.Add((object)"Mali");
            this.chkBoxCountries.Items.Add((object)"Malta");
            this.chkBoxCountries.Items.Add((object)"Mauritania");
            this.chkBoxCountries.Items.Add((object)"Mauritius");
            this.chkBoxCountries.Items.Add((object)"Mexico");
            this.chkBoxCountries.Items.Add((object)"Micronesia");
            this.chkBoxCountries.Items.Add((object)"Moldova");
            this.chkBoxCountries.Items.Add((object)"Monaco");
            this.chkBoxCountries.Items.Add((object)"Mongolia");
            this.chkBoxCountries.Items.Add((object)"Montenegro");
            this.chkBoxCountries.Items.Add((object)"Montserrat");
            this.chkBoxCountries.Items.Add((object)"Morocco");
            this.chkBoxCountries.Items.Add((object)"Mozambique");
            this.chkBoxCountries.Items.Add((object)"Namibia");
            this.chkBoxCountries.Items.Add((object)"Nepal");
            this.chkBoxCountries.Items.Add((object)"Netherlands");
            this.chkBoxCountries.Items.Add((object)"Netherlands Antilles");
            this.chkBoxCountries.Items.Add((object)"New Caledonia");
            this.chkBoxCountries.Items.Add((object)"New Zealand");
            this.chkBoxCountries.Items.Add((object)"Nicaragua");
            this.chkBoxCountries.Items.Add((object)"Niger");
            this.chkBoxCountries.Items.Add((object)"Norway");
            this.chkBoxCountries.Items.Add((object)"Oman");
            this.chkBoxCountries.Items.Add((object)"Pakistan");
            this.chkBoxCountries.Items.Add((object)"Panama");
            this.chkBoxCountries.Items.Add((object)"Papua New Guinea");
            this.chkBoxCountries.Items.Add((object)"Paraguay");
            this.chkBoxCountries.Items.Add((object)"Peru");
            this.chkBoxCountries.Items.Add((object)"Philippines");
            this.chkBoxCountries.Items.Add((object)"Poland");
            this.chkBoxCountries.Items.Add((object)"Portugal");
            this.chkBoxCountries.Items.Add((object)"Puerto Rico");
            this.chkBoxCountries.Items.Add((object)"Qatar");
            this.chkBoxCountries.Items.Add((object)"Reunion");
            this.chkBoxCountries.Items.Add((object)"Romania");
            this.chkBoxCountries.Items.Add((object)"Russia");
            this.chkBoxCountries.Items.Add((object)"Rwanda");
            this.chkBoxCountries.Items.Add((object)"Saint Kitts and Nevis");
            this.chkBoxCountries.Items.Add((object)"Saint Lucia");
            this.chkBoxCountries.Items.Add((object)"San Marino");
            this.chkBoxCountries.Items.Add((object)"Samoa");
            this.chkBoxCountries.Items.Add((object)"Satellite Networks");
            this.chkBoxCountries.Items.Add((object)"Saudi Arabia");
            this.chkBoxCountries.Items.Add((object)"Senegal");
            this.chkBoxCountries.Items.Add((object)"Serbia");
            this.chkBoxCountries.Items.Add((object)"Seychelles");
            this.chkBoxCountries.Items.Add((object)"Sierra Leone");
            this.chkBoxCountries.Items.Add((object)"Singapore");
            this.chkBoxCountries.Items.Add((object)"Slovakia");
            this.chkBoxCountries.Items.Add((object)"Slovenia");
            this.chkBoxCountries.Items.Add((object)"Solomon Islands");
            this.chkBoxCountries.Items.Add((object)"Somalia");
            this.chkBoxCountries.Items.Add((object)"South Africa");
            this.chkBoxCountries.Items.Add((object)"Spain");
            this.chkBoxCountries.Items.Add((object)"Sri Lanka");
            this.chkBoxCountries.Items.Add((object)"St. Pierre and Miquelon");
            this.chkBoxCountries.Items.Add((object)"St. Vincent and Gren.");
            this.chkBoxCountries.Items.Add((object)"Sudan");
            this.chkBoxCountries.Items.Add((object)"Suriname");
            this.chkBoxCountries.Items.Add((object)"Swaziland");
            this.chkBoxCountries.Items.Add((object)"Sweden");
            this.chkBoxCountries.Items.Add((object)"Switzerland");
            this.chkBoxCountries.Items.Add((object)"Syrian Arab Republic");
            this.chkBoxCountries.Items.Add((object)"Taiwan");
            this.chkBoxCountries.Items.Add((object)"Tajikistan");
            this.chkBoxCountries.Items.Add((object)"Tanzania");
            this.chkBoxCountries.Items.Add((object)"Thailand");
            this.chkBoxCountries.Items.Add((object)"Timor-Leste");
            this.chkBoxCountries.Items.Add((object)"Togo");
            this.chkBoxCountries.Items.Add((object)"Tonga");
            this.chkBoxCountries.Items.Add((object)"Trinidad and Tobago");
            this.chkBoxCountries.Items.Add((object)"Tunisia");
            this.chkBoxCountries.Items.Add((object)"Turkey");
            this.chkBoxCountries.Items.Add((object)"Turkmenistan");
            this.chkBoxCountries.Items.Add((object)"Uganda");
            this.chkBoxCountries.Items.Add((object)"Ukraine");
            this.chkBoxCountries.Items.Add((object)"United Arab Emirates");
            this.chkBoxCountries.Items.Add((object)"United Kingdom");
            this.chkBoxCountries.Items.Add((object)"United States");
            this.chkBoxCountries.Items.Add((object)"Uruguay");
            this.chkBoxCountries.Items.Add((object)"Uzbekistan");
            this.chkBoxCountries.Items.Add((object)"Vanuatu");
            this.chkBoxCountries.Items.Add((object)"Venezuela");
            this.chkBoxCountries.Items.Add((object)"Viet Nam");
            this.chkBoxCountries.Items.Add((object)"Virgin Islands, U.S.");
            this.chkBoxCountries.Items.Add((object)"Yemen");
            this.chkBoxCountries.Items.Add((object)"Zambia");
            this.chkBoxCountries.Items.Add((object)"Zimbabwe");
        }
    }
}
