using System.Collections.Generic;


namespace CCS7Manager
{
    class Countries
    {
        public Dictionary<string, List<string>> CountryList;
        public Countries ()
        {
            CountryList = new Dictionary<string, List<string>>();
            CountryList.Add("Afghanistan", new List<string>() { "Afghanistan" });
            CountryList.Add("Albania", new List<string>() { "Albania" });
            CountryList.Add("Algeria", new List<string>() { "Algeria" });
            CountryList.Add("American Samoa", new List<string>() { "American Samoa" });
            CountryList.Add("Andorra", new List<string>() { "Andorra" });
            CountryList.Add("Angola", new List<string>() { "Angola" });
            CountryList.Add("Anguilla", new List<string>() { "Anguilla" });
            CountryList.Add("Antigua and Barbuda", new List<string>()  {"Antigua and Barbuda" });
            CountryList.Add("Argentina Republic", new List<string>() { "Argentina Republic" });
            CountryList.Add("Armenia", new List<string>() { "Armenia" });
            CountryList.Add("Aruba", new List<string>() { "Aruba" });
            CountryList.Add("Australia", new List<string>() { "Australia" });
            CountryList.Add("Austria", new List<string>() { "Austria" });
            CountryList.Add("Azerbaijan", new List<string>() { "Azerbaijan" });
            CountryList.Add("Bahamas", new List<string>() { "Bahamas" });
            CountryList.Add("Bahrain", new List<string>() { "Bahrain" });
            CountryList.Add("Bangladesh", new List<string>() { "Bangladesh" });
            CountryList.Add("Barbados", new List<string>() { "Barbados" });
            CountryList.Add("Belarus", new List<string>() { "Belarus" });
            CountryList.Add("Belgium", new List<string>() { "Belgium" });
            CountryList.Add("Belize", new List<string>() { "Belize" });
            CountryList.Add("Benin", new List<string>() { "Benin" });
            CountryList.Add("Bermuda", new List<string>() { "Bermuda" });
            CountryList.Add("Bhutan", new List<string>() { "Bhutan" });
            CountryList.Add("Bolivia", new List<string>() { "Bolivia" });
            CountryList.Add("Bosnia And Herzegovin", new List<string>() { "Bosnia And Herzegovin" });
            CountryList.Add("Botswana", new List<string>() { "Botswana" });
            CountryList.Add("Brazil", new List<string>() { "Brazil" });
            CountryList.Add("British Virgin Islands", new List<string>() { "British Virgin Islands" });
            CountryList.Add("Brunei Darussalam", new List<string>() { "Brunei Darussalam" });
            CountryList.Add("Bulgaria", new List<string>() { "Bulgaria" });
            CountryList.Add("Burkina Faso", new List<string>() { "Burkina Faso" });
            CountryList.Add("Burma", new List<string>() { "Burma" });
            CountryList.Add("Burundi", new List<string>() { "Burundi" });
            CountryList.Add("Cambodia", new List<string>() { "Cambodia" });
            CountryList.Add("Canada", new List<string>() { "Canada" });
            CountryList.Add("Cayman Islands", new List<string>() { "Cayman Islands" });
            CountryList.Add("Chile", new List<string>() { "Chile" });
            CountryList.Add("China", new List<string>() { "China" });
            CountryList.Add("Colombia", new List<string>() { "Colombia" , "Columbia" });
            CountryList.Add("Comoros", new List<string>() { "Comoros" });
            CountryList.Add("Congo, Dem. Rep.", new List<string>() { "Congo, Dem. Rep." });
            CountryList.Add("Cook Islands", new List<string>() { "Cook Islands" });
            CountryList.Add("Corse", new List<string>() { "Korsika" });
            CountryList.Add("Costa Rica", new List<string>() { "Costa Rica" });
            CountryList.Add("Croatia", new List<string>() { "Croatia" });
            CountryList.Add("Cuba", new List<string>() { "Cuba" });
            CountryList.Add("Cyprus", new List<string>() { "Cyprus" });
            CountryList.Add("Czech Republic", new List<string>() { "Czech Republic" });
            CountryList.Add("Denmark", new List<string>() { "Denmark" });
            CountryList.Add("Djibouti", new List<string>() { "Djibouti" });
            CountryList.Add("Dominica", new List<string>() { "Dominica" });
            CountryList.Add("Dominican Republic", new List<string>() { "Dominican Republic" });
            CountryList.Add("Ecuador", new List<string>() { "Ecuador" });
            CountryList.Add("Egypt", new List<string>() { "Egypt" });
            CountryList.Add("El Salvador", new List<string>() { "El Salvador" });
            CountryList.Add("Eritrea", new List<string>() { "Eritrea" });
            CountryList.Add("Estonia", new List<string>() { "Estonia" });
            CountryList.Add("Ethiopia", new List<string>() { "Ethiopia" });
            CountryList.Add("Faroe Islands", new List<string>() { "Faroe Islands" });
            CountryList.Add("Fiji", new List<string>() { "Fiji" });
            CountryList.Add("Finland", new List<string>() { "Finland" });
            CountryList.Add("France", new List<string>() { "France" });
            CountryList.Add("French Guiana", new List<string>() { "French Guiana" });
            CountryList.Add("French Polynesia", new List<string>() { "French Polynesia" });
            CountryList.Add("Gambia", new List<string>() { "Gambia" });
            CountryList.Add("Georgia", new List<string>() { "Georgia" });
            CountryList.Add("Germany", new List<string>() { "Germany" });
            CountryList.Add("Gibraltar", new List<string>() { "Gibraltar" });
            CountryList.Add("Greece", new List<string>() { "Greece" });
            CountryList.Add("Greenland", new List<string>() { "Greenland" });
            CountryList.Add("Grenada", new List<string>() { "Grenada" });
            CountryList.Add("Guadeloupe", new List<string>() { "Guadeloupe" });
            CountryList.Add("Guam", new List<string>() { "Guam" });
            CountryList.Add("Guatemala", new List<string>() { "Guatemala" });
            CountryList.Add("Guinea", new List<string>() { "Guinea" });
            CountryList.Add("Guinea-Bissau", new List<string>() { "Guinea-Bissau" });
            CountryList.Add("Guyana", new List<string>() { "Guyana" });
            CountryList.Add("Haiti", new List<string>() { "Haiti" });
            CountryList.Add("Honduras", new List<string>() { "Honduras" });
            CountryList.Add("Hong Kong", new List<string>() { "Hong Kong" });
            CountryList.Add("Hungary", new List<string>() { "Hungary" });
            CountryList.Add("Iceland", new List<string>() { "Iceland" });
            CountryList.Add("India", new List<string>() { "India" });
            CountryList.Add("Indonesia", new List<string>() { "Indonesia" });
            CountryList.Add("Iran", new List<string>() { "Iran" });
            CountryList.Add("Iraq", new List<string>() { "Iraq" });
            CountryList.Add("Ireland", new List<string>() { "Ireland" });
            CountryList.Add("Israel", new List<string>() { "Israel" });
            CountryList.Add("Italy", new List<string>() { "Italy" });
            CountryList.Add("Ivory Coast", new List<string>() { "Ivory Coast" });
            CountryList.Add("Jamaica", new List<string>() { "Jamaica" });
            CountryList.Add("Japan", new List<string>() { "Japan" });
            CountryList.Add("Jordan", new List<string>() { "Jordan" });
            CountryList.Add("Kazakhstan", new List<string>() { "Kazakhstan", "Akmola" });
            CountryList.Add("Kenya", new List<string>() { "Kenya" });
            CountryList.Add("Kiribati", new List<string>() { "Kiribati" });
            CountryList.Add("Korea S, Republic of", new List<string>() { "Korea S, Republic of" });
            CountryList.Add("Kuwait", new List<string>() { "Kuwait" });
            CountryList.Add("Kyrgyzstan", new List<string>() { "Kyrgyzstan" });
            CountryList.Add("Laos P.D.R.", new List<string>() { "Laos P.D.R." });
            CountryList.Add("Latvia", new List<string>() { "Latvia" });
            CountryList.Add("Lebanon", new List<string>() { "Lebanon" });
            CountryList.Add("Lesotho", new List<string>() { "Lesotho" });
            CountryList.Add("Liberia", new List<string>() { "Liberia" });
            CountryList.Add("Libya", new List<string>() { "Libya" });
            CountryList.Add("Liechtenstein", new List<string>() { "Liechtenstein" });
            CountryList.Add("Lithuania", new List<string>() { "Lithuania" });
            CountryList.Add("Luxembourg", new List<string>() { "Luxembourg" });
            CountryList.Add("Macao, China", new List<string>() { "Macao, China" });
            CountryList.Add("Macedonia", new List<string>() { "Macedonia" });
            CountryList.Add("Madagascar", new List<string>() { "Madagascar" });
            CountryList.Add("Malawi", new List<string>() { "Malawi" });
            CountryList.Add("Malaysia", new List<string>() { "Malaysia" });
            CountryList.Add("Maldives", new List<string>() { "Maldives" });
            CountryList.Add("Mali", new List<string>() { "Mali" });
            CountryList.Add("Malta", new List<string>() { "Malta" });
            CountryList.Add("Martinique", new List<string>() { "Martinique" });
            CountryList.Add("Mauritania", new List<string>() { "Mauritania" });
            CountryList.Add("Mauritius", new List<string>() { "Mauritius" });
            CountryList.Add("Mexico", new List<string>() { "Mexico" });
            CountryList.Add("Micronesia", new List<string>() { "Micronesia" });
            CountryList.Add("Moldova", new List<string>() { "Moldova" });
            CountryList.Add("Monaco", new List<string>() { "Monaco" });
            CountryList.Add("Mongolia", new List<string>() { "Mongolia" });
            CountryList.Add("Montenegro", new List<string>() { "Montenegro" });
            CountryList.Add("Montserrat", new List<string>() { "Montserrat" });
            CountryList.Add("Morocco", new List<string>() { "Marocco", "Morocco" });
            CountryList.Add("Mozambique", new List<string>() { "Mozambique" });
            CountryList.Add("Namibia", new List<string>() { "Namibia" });
            CountryList.Add("Nepal", new List<string>() { "Nepal" });
            CountryList.Add("Netherlands", new List<string>() { "Netherlands" });
            CountryList.Add("Netherlands Antilles", new List<string>() { "Netherlands Antilles" });
            CountryList.Add("New Caledonia", new List<string>() { "New Caledonia" });
            CountryList.Add("New Zealand", new List<string>() { "New Zealand" });
            CountryList.Add("Nicaragua", new List<string>() { "Nicaragua" });
            CountryList.Add("Niger", new List<string>() { "Niger" });
            CountryList.Add("Norway", new List<string>() { "Norway" });
            CountryList.Add("Oman", new List<string>() { "Oman" });
            CountryList.Add("Pakistan", new List<string>() { "Pakistan" });
            CountryList.Add("Panama", new List<string>() { "Panama" });
            CountryList.Add("Papua New Guinea", new List<string>() { "Papua New Guinea" });
            CountryList.Add("Paraguay", new List<string>() { "Paraguay" });
            CountryList.Add("Peru", new List<string>() { "Peru" });
            CountryList.Add("Philippines", new List<string>() { "Philippines" });
            CountryList.Add("Poland", new List<string>() { "Poland" });
            CountryList.Add("Portugal", new List<string>() { "Portugal" });
            CountryList.Add("Puerto Rico", new List<string>() { "Puerto Rico" });
            CountryList.Add("Qatar", new List<string>() { "Qatar" });
            CountryList.Add("Reunion", new List<string>() { "Reunion" });
            CountryList.Add("Romania", new List<string>() { "Romania" });
            CountryList.Add("Russia", new List<string>() { "Russia" });
            CountryList.Add("Rwanda", new List<string>() { "Rwanda" });
            CountryList.Add("Saint Kitts and Nevis", new List<string>() { "Saint Kitts and Nevis" });
            CountryList.Add("Saint Lucia", new List<string>() { "Saint Lucia" });
            CountryList.Add("San Marino", new List<string>() { "San Marino" });
            CountryList.Add("Samoa", new List<string>() { "Samoa" });
            CountryList.Add("Satellite Networks", new List<string>() { "Satellite Networks" });
            CountryList.Add("Saudi Arabia", new List<string>() { "Saudi Arabia" });
            CountryList.Add("Senegal", new List<string>() { "Senegal" });
            CountryList.Add("Serbia", new List<string>() { "Serbia" });
            CountryList.Add("Seychelles", new List<string>() { "Seychelles" });
            CountryList.Add("Sierra Leone", new List<string>() { "Sierra Leone" });
            CountryList.Add("Singapore", new List<string>() { "Singapore" });
            CountryList.Add("Slovakia", new List<string>() { "Slovakia" });
            CountryList.Add("Slovenia", new List<string>() { "Slovenia" });
            CountryList.Add("Solomon Islands", new List<string>() { "Solomon Islands" });
            CountryList.Add("Somalia", new List<string>() { "Somalia" });
            CountryList.Add("South Africa", new List<string>() { "South Africa" });
            CountryList.Add("Spain", new List<string>() { "Spain" });
            CountryList.Add("Sri Lanka", new List<string>() { "Sri Lanka" });
            CountryList.Add("St. Pierre and Miquelon", new List<string>() { "St. Pierre and Miquelon" });
            CountryList.Add("St. Vincent and Gren.", new List<string>() { "St. Vincent and Gren." });
            CountryList.Add("Sudan", new List<string>() { "Sudan" });
            CountryList.Add("Suriname", new List<string>() { "Suriname" });
            CountryList.Add("Swaziland", new List<string>() { "Swaziland" });
            CountryList.Add("Sweden", new List<string>() { "Sweden" });
            CountryList.Add("Switzerland", new List<string>() { "Switzerland" });
            CountryList.Add("Syrian Arab Republic", new List<string>() { "Syrian Arab Republic" });
            CountryList.Add("Taiwan", new List<string>() { "Taiwan" });
            CountryList.Add("Tajikistan", new List<string>() { "Tajikistan" });
            CountryList.Add("Tanzania", new List<string>() { "Tanzania" });
            CountryList.Add("Thailand", new List<string>() { "Thailand" });
            CountryList.Add("Timor-Leste", new List<string>() { "Timor-Leste" });
            CountryList.Add("Togo", new List<string>() { "Togo" });
            CountryList.Add("Tonga", new List<string>() { "Tonga" });
            CountryList.Add("Trinidad and Tobago", new List<string>() { "Trinidad and Tobago" });
            CountryList.Add("Tunisia", new List<string>() { "Tunisia" });
            CountryList.Add("Turkey", new List<string>() { "Turkey" });
            CountryList.Add("Turkmenistan", new List<string>() { "Turkmenistan" });
            CountryList.Add("Uganda", new List<string>() { "Uganda" });
            CountryList.Add("Ukraine", new List<string>() { "Ukraine" });
            CountryList.Add("United Arab Emirates", new List<string>() { "United Arab Emirates" });
            CountryList.Add("United Kingdom", new List<string>() { "United Kingdom" });
            CountryList.Add("United States", new List<string>() { "United States" });
            CountryList.Add("Uruguay", new List<string>() { "Uruguay" });
            CountryList.Add("Uzbekistan", new List<string>() { "Uzbekistan" });
            CountryList.Add("Vanuatu", new List<string>() { "Vanuatu" });
            CountryList.Add("Venezuela", new List<string>() { "Venezuela" });
            CountryList.Add("Viet Nam", new List<string>() { "Viet Nam" });
            CountryList.Add("Virgin Islands, U.S.", new List<string>() { "Virgin Islands, U.S." });
            CountryList.Add("Yemen", new List<string>() { "Yemen" });
            CountryList.Add("Zambia", new List<string>() { "Zambia" });
            CountryList.Add("Zimbabwe", new List<string>() { "Zimbabwe" });
        }
    }
}
